apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  labels:
    app: swath
  name: redirect-http
  namespace: swath
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT