apiVersion: v1
kind: Service
metadata:
  name: swath-lb
  namespace: swath
spec:
  type: NodePort
  selector:
    app: swath
  ports:
    - name: 80-9009 
      protocol: TCP
      port: 80
      targetPort: 9009
  selector:
    app: swath

---

apiVersion: v1
kind: Service
metadata:
  name: swath-lb-020
  namespace: swath
spec:
  type: NodePort
  selector:
    app: swath020
  ports:
    - name: 80-9009 
      protocol: TCP
      port: 80
      targetPort: 9009
  selector:
    app: swath020


---

apiVersion: v1
kind: Service
metadata:
  name: swath-lb-015
  namespace: swath
spec:
  type: NodePort
  selector:
    app: swath015
  ports:
    - name: 80-9009 
      protocol: TCP
      port: 80
      targetPort: 9009
  selector:
    app: swath015